# autoremove-torrents lifecycle using pipx and systemd timer.

if [[ -n "${SEEDBOX_COMPONENT_AUTOREMOVE_TORRENTS_SOURCED:-}" ]]; then
  return 0
fi
readonly SEEDBOX_COMPONENT_AUTOREMOVE_TORRENTS_SOURCED=1

autoremove_torrents::usage() {
  if ui::zh; then
    cat <<'USAGE'
用法：
  seedboxctl autoremove-torrents install --user 用户名 [--enable-autoremove]
  seedboxctl autoremove-torrents upgrade --user 用户名
  seedboxctl autoremove-torrents uninstall --user 用户名 [--purge] [--yes]
  seedboxctl autoremove-torrents status --user 用户名

安装会在目标用户 HOME 下使用 pipx，避免在 Debian/Ubuntu 上使用全局 pip。
默认生成的是安全配置模板；启用自动删除前请先编辑配置。
USAGE
  else
    cat <<'USAGE'
Usage:
  seedboxctl autoremove-torrents install --user USER [--enable-autoremove]
  seedboxctl autoremove-torrents upgrade --user USER
  seedboxctl autoremove-torrents uninstall --user USER [--purge] [--yes]
  seedboxctl autoremove-torrents status --user USER

Install uses pipx under the target user's home, avoiding global pip on Debian/Ubuntu.
The default generated config is a safe template; edit it before enabling automatic removal.
USAGE
  fi
}

autoremove_torrents::cli() {
  local sub="${1:-help}"
  [[ $# -gt 0 ]] && shift || true
  case "${sub}" in
    install) args::parse "$@"; log::init autoremove-install; autoremove_torrents::install_from_parsed ;;
    upgrade) args::parse "$@"; log::init autoremove-upgrade; autoremove_torrents::upgrade_from_parsed ;;
    uninstall|remove) args::parse "$@"; log::init autoremove-uninstall; autoremove_torrents::uninstall_from_parsed ;;
    status) args::parse "$@"; log::init autoremove-status; autoremove_torrents::status_from_parsed ;;
    help|-h|--help) autoremove_torrents::usage ;;
    *) ui::error "$(ui::tr "未知 autoremove-torrents 命令：${sub}" "Unknown autoremove-torrents command: ${sub}")"; autoremove_torrents::usage; return 2 ;;
  esac
}

autoremove_torrents::load_args() {
  ART_USER="$(args::get user)"
  [[ -n "${ART_USER}" ]] || { ui::error "$(ui::tr "需要 --user" "--user is required")"; return 2; }
  validate::die_username "${ART_USER}" || return 2
  ART_HOME="$(user::home "${ART_USER}" 2>/dev/null || true)"
  ART_CONFIG_DIR="${ART_HOME}/.config/autoremove-torrents"
  ART_CONFIG="${ART_CONFIG_DIR}/config.yml"
  ART_BIN="${ART_HOME}/.local/bin/autoremove-torrents"
  ART_SERVICE="seedbox-autoremove-torrents-${ART_USER}.service"
  ART_TIMER="seedbox-autoremove-torrents-${ART_USER}.timer"
}

autoremove_torrents::preflight() {
  detect::assert_root || return $?
  detect::assert_supported_os || return $?
  user::exists "${ART_USER}" || { ui::error "$(ui::tr "用户不存在：${ART_USER}" "User does not exist: ${ART_USER}")"; return 1; }
  ART_HOME="$(user::home "${ART_USER}")" || return $?
}

autoremove_torrents::install_packages() {
  apt::update || return $?
  apt::ensure_packages python3 python3-venv pipx || return $?
}

autoremove_torrents::pipx_install() {
  user::run "${ART_USER}" python3 -m pipx install --force autoremove-torrents
}

autoremove_torrents::write_config() {
  install -d -m 0700 -o "${ART_USER}" -g "${ART_USER}" "${ART_CONFIG_DIR}"
  if [[ ! -e "${ART_CONFIG}" ]] || args::has force; then
    fs::write_file "${ART_CONFIG}" 0600 "${ART_USER}" "${ART_USER}" <<EOF_CONFIG
# autoremove-torrents config template generated by seedboxctl.
# Edit before enabling the timer. Documentation: https://autoremove-torrents.readthedocs.io/
#
# Example skeleton:
# my_task:
#   client: qbittorrent
#   host: http://127.0.0.1:8080
#   username: "${ART_USER}"
#   password: "CHANGE_ME"
#   strategies:
#     my_strategy:
#       categories:
#         - freeleech
#       remove: seeding_time > 604800
EOF_CONFIG
  fi
}

autoremove_torrents::write_units() {
  systemd::write_unit "${ART_SERVICE}" <<EOF_SERVICE
[Unit]
Description=autoremove-torrents for ${ART_USER}
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=${ART_USER}
Group=${ART_USER}
Environment=HOME=${ART_HOME}
ExecStart=${ART_BIN} --conf=${ART_CONFIG}
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=full

[Install]
WantedBy=multi-user.target
EOF_SERVICE

  systemd::write_unit "${ART_TIMER}" <<EOF_TIMER
[Unit]
Description=Run autoremove-torrents for ${ART_USER} periodically

[Timer]
OnBootSec=10min
OnUnitActiveSec=10min
Persistent=true
Unit=${ART_SERVICE}

[Install]
WantedBy=timers.target
EOF_TIMER

  if args::has enable_autoremove; then
    systemctl enable --now "${ART_TIMER}"
  else
    systemctl disable "${ART_TIMER}" 2>/dev/null || true
  fi
}

autoremove_torrents::write_state() {
  state::write autoremove-torrents "${ART_USER}" <<EOF_STATE
component=autoremove-torrents
user=${ART_USER}
binary=${ART_BIN}
config=${ART_CONFIG}
service=${ART_SERVICE}
timer=${ART_TIMER}
enabled=$(args::has enable_autoremove && printf yes || printf no)
installed_at=$(date '+%Y-%m-%dT%H:%M:%S%z')
EOF_STATE
}

autoremove_torrents::install_from_parsed() {
  autoremove_torrents::load_args || return $?
  ui::heading "$(ui::tr "正在安装 autoremove-torrents" "Installing autoremove-torrents")"
  ui::kv "$(ui::tr "用户" "User")" "${ART_USER}"
  ui::log_location
  printf '\n'
  runner::must art.preflight "$(ui::tr "安装前检查" "Preflight checks")" "" autoremove_torrents::preflight || return $?
  runner::must art.packages "$(ui::tr "安装 Python/pipx 软件包" "Install Python/pipx packages")" "" autoremove_torrents::install_packages || return $?
  runner::must art.pipx "$(ui::tr "使用 pipx 安装 autoremove-torrents" "Install autoremove-torrents with pipx")" "" autoremove_torrents::pipx_install || return $?
  runner::must art.config "$(ui::tr "写入安全配置模板" "Write safe config template")" "" autoremove_torrents::write_config || return $?
  runner::must art.units "$(ui::tr "写入 systemd 服务/定时器" "Write systemd service/timer")" "${ART_SERVICE}" autoremove_torrents::write_units || return $?
  runner::must art.state "$(ui::tr "保存 autoremove-torrents 状态" "Save autoremove-torrents state")" "" autoremove_torrents::write_state || return $?
  ui::success "$(ui::tr "autoremove-torrents 已安装。配置：${ART_CONFIG}" "autoremove-torrents installed. Config: ${ART_CONFIG}")"
  if ! args::has enable_autoremove; then
    ui::warn "$(ui::tr "定时器已安装但未启用。编辑配置后执行：systemctl enable --now ${ART_TIMER}" "Timer is installed but disabled. Enable after editing config: systemctl enable --now ${ART_TIMER}")"
  fi
}

autoremove_torrents::read_state() {
  local user="$1" path
  path="$(state::path autoremove-torrents "${user}")"
  [[ -r "${path}" ]] || { ui::error "$(ui::tr "未找到 ${user} 的 autoremove-torrents 状态。" "No autoremove-torrents state found for ${user}.")"; return 1; }
  ART_USER="${user}"
  ART_BIN="$(state::get "${path}" binary)"
  ART_CONFIG="$(state::get "${path}" config)"
  ART_SERVICE="$(state::get "${path}" service)"
  ART_TIMER="$(state::get "${path}" timer)"
  ART_HOME="$(user::home "${user}")"
  ART_CONFIG_DIR="$(dirname -- "${ART_CONFIG}")"
}

autoremove_torrents::upgrade_from_parsed() {
  local user
  user="$(args::get user)"
  [[ -n "${user}" ]] || { ui::error "$(ui::tr "需要 --user" "--user is required")"; return 2; }
  autoremove_torrents::read_state "${user}"
  ui::heading "$(ui::tr "正在为 ${ART_USER} 升级 autoremove-torrents" "Upgrading autoremove-torrents for ${ART_USER}")"
  ui::log_location
  printf '\n'
  runner::must art.upgrade "$(ui::tr "使用 pipx 升级 autoremove-torrents" "Upgrade autoremove-torrents with pipx")" "" user::run "${ART_USER}" python3 -m pipx upgrade autoremove-torrents || return $?
  ui::success "$(ui::tr "已为 ${ART_USER} 升级 autoremove-torrents。" "autoremove-torrents upgraded for ${ART_USER}.")"
}

autoremove_torrents::uninstall_from_parsed() {
  local user
  user="$(args::get user)"
  [[ -n "${user}" ]] || { ui::error "$(ui::tr "需要 --user" "--user is required")"; return 2; }
  autoremove_torrents::read_state "${user}"
  systemctl disable --now "${ART_TIMER}" 2>/dev/null || true
  rm -f -- "/etc/systemd/system/${ART_SERVICE}" "/etc/systemd/system/${ART_TIMER}"
  systemctl daemon-reload 2>/dev/null || true
  user::run "${ART_USER}" python3 -m pipx uninstall autoremove-torrents 2>/dev/null || true
  if args::has purge; then
    args::has yes || { ui::error "$(ui::tr "使用 --purge 时必须同时传入 --yes。" "Use --yes with --purge.")"; return 1; }
    ui::warn "$(ui::tr "清理将删除 autoremove-torrents 配置目录：${ART_CONFIG_DIR}" "Purge will remove autoremove-torrents config directory: ${ART_CONFIG_DIR}")"
    rm -rf -- "${ART_CONFIG_DIR}"
  fi
  state::remove autoremove-torrents "${ART_USER}"
  ui::success "$(ui::tr "已为 ${ART_USER} 卸载 autoremove-torrents。" "autoremove-torrents uninstalled for ${ART_USER}.")"
}

autoremove_torrents::status_from_parsed() {
  local user
  user="$(args::get user)"
  [[ -n "${user}" ]] || { ui::error "$(ui::tr "需要 --user" "--user is required")"; return 2; }
  autoremove_torrents::read_state "${user}"
  systemctl status "${ART_TIMER}" --no-pager -l || true
  systemctl status "${ART_SERVICE}" --no-pager -l || true
}
